configs : Updating the setup-environment script
New additions to the script :
1) Debug, debug+kasan builds are supported
2) QBuilder, 806x_caf and upstream profiles are not supported
3) Sort the profiles before displaying them

Change-Id: I72db66bf19808cbb1e041f38e7c0703644696406
Signed-off-by: Sandhya KS <quic_sandhyks@quicinc.com>

diff --git a/setup-environment b/setup-environment
--- a/setup-environment
+++ b/setup-environment
@@ -14,8 +14,13 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
+SCRIPT_DIR=$(dirname ${BASH_SOURCE[0]})
+TOP_DIR="$SCRIPT_DIR/../../../"
+declare -a profile
+declare -a debug
+declare -a profile_name
 
-
+ret_val=1
 if [ "$#" -gt 0 ]; then
     if [ "$1" == "-h" ]; then
         echo "Usage: Provide target, arch and profile type for entire build (Please run \"make clean\" if this is an existing workspace)" >&2
@@ -24,103 +29,136 @@ if [ "$#" -gt 0 ]; then
 fi
 
 #echo "Help options, Run command with -h [$0 -h]"
-echo ""
-echo -e "\t1) ipq807x ( Hawkeye )"
-echo -e "\t2) ipq60xx ( Cypress )"
-echo -e "\t3) ipq50xx ( Maple ) "
-echo -e "\t4) ipq95xx ( Alder ) "
-read -p "Please enter your choice of target[1..4] : " in_soc
-echo ""
-
-if [[ $in_soc -lt 1 || $in_soc -gt 4 ]]; then
-    echo "wrong input.. exit"
-    return -1
-fi
-
-echo -e "\t1) 32 Bit"
-echo -e "\t2) 64 bit"
-read -p "Please enter your choice of build type[1..2] : " in_arch
-echo ""
-
-if [[ $in_arch -lt 1 || $in_arch -gt 2 ]]; then
-    echo "wrong input.. exit"
-    return -1
-fi
-
-echo -e "\t1) Premium"
-echo -e "\t2) Enterprise"
-echo -e "\t3) Open"
-echo -e "\t4) 512"
-echo -e "\t5) 512 Enterprise"
-echo -e "\t6) 512 Open"
-echo -e "\t7) 256"
-read -p "Please enter your choice of profile[1..7] : " in_profile
-echo ""
-
-if [[ $in_profile -lt 1 || $in_profile -gt 7 ]]; then
-    echo "wrong input.. exit"
-    return -1
-fi
-
-declare -a profile_list
-declare -a soc_list
-declare -a arch_list
-
-profile_list=("Premium" "Enterprise" "Open" "512" "512Enterprise" "512Open" "256")
-cfg_profile_list=("premium" "enterprise" "open" "512" "512enterprise" "512open" "256")
 soc_list=("ipq807x" "ipq60xx" "ipq50xx" "ipq95xx")
 arch_list=("32" "64")
 
-cfg_profile=${cfg_profile_list[$in_profile-1]}
-soc=${soc_list[$in_soc-1]}
-arch=${arch_list[$in_arch-1]}
-profile=${profile_list[$in_profile-1]}
+populate_profile_list()
+{
+	profile=()
+	profile_name=()
+	for qsdk_profile in $(find $SCRIPT_DIR/ -name 'ipq*.config' ! -name '*qbuilder*' | sort );do
+		filename=$(basename $qsdk_profile)
+		profile+=( "${filename%.*}" )
+		QSDK_profile=$(grep -oP "CONFIG_TARGET_.*\KQSDK_[a-zA-Z0-9]*" $qsdk_profile)
+		name=${QSDK_profile:-"None"}
+		profile_name+=( "$name" )
+	done
+}
 
-if [ $profile = "512Enterprise" ]; then
-    profile="Enterprise"
-elif [ $profile = "512Open" ]; then
-    profile="Open"
+read_inputs()
+{
+	echo ""
+	echo -e "\t1) ipq807x ( Hawkeye )"
+	echo -e "\t2) ipq60xx ( Cypress )"
+	echo -e "\t3) ipq50xx ( Maple ) "
+	echo -e "\t4) ipq95xx ( Alder ) "
+	read -p "Please enter your choice of target[1..4] : " in_soc
+	echo ""
+
+	if [[ $in_soc -lt 1 || $in_soc -gt 4 ]]; then
+	        echo "Wrong input.. exiting"
+		return 0
+	fi
+
+	echo -e "\t1) 32 Bit"
+	echo -e "\t2) 64 bit"
+	read -p "Please enter your choice of build type[1..2] : " in_arch
+	echo ""
+
+	if [[ $in_arch -lt 1 || $in_arch -gt 2 ]]; then
+	        echo "Wrong input.. exiting"
+		return 0
+	fi
+
+	qsdk_target=${soc_list[$in_soc-1]}
+	arch=${arch_list[$in_arch-1]}
+	if [ "$arch" -eq "64" ];then
+		qsdk_subtarget="generic"
+	else if [ "$arch" -eq "32" ];then
+		qsdk_subtarget="${qsdk_target}_32"
+		fi
+	fi
+
+	echo -e "\n\033[36m**** List of supported QSDK profiles *****\033[0m"
+	populate_profile_list
+	index=1
+	for i in ${profile[@]};do
+		echo -e "\t$index) ${i:4}"
+		index=$(( $index+1 ))
+	done
+	read -p "Choose the profile [1..${#profile[@]}] : " input
+	if [[ $input -lt 1 || $input -gt ${#profile[@]} ]];then
+		echo "Please enter a valid input...Exiting"
+		return 0
+	fi
+	declare qsdk_profile=${profile[$(( $input -1 ))]}
+	pfile=${profile[$(( $input -1 ))]}
+	pname=${profile_name[$(( $input -1 ))]}
+	echo -e "\n\033[36mSelected configuration: ${qsdk_target} - ${qsdk_subtarget} - ${qsdk_profile}\033[0m"
+	read -p "Debug build required ? [y/n] : " debug_in
+	case $debug_in in
+		'y') debug=("Debug" "Debug+Kasan")
+			# Check for debug builds
+			index=1
+			for i in ${debug[@]};do
+				echo -e "\t$index) $i"
+				index=$(( $index+1 ))
+			done
+
+			read -p "Choose the option for debug build : " debug_input
+			case $debug_input in
+				1)	if [[ "$pname" = QSDK_16M ]];then
+					       cat $SCRIPT_DIR/${pfile}.config \
+						       $SCRIPT_DIR/ipq_debug_16M > $TOP_DIR/.config
+				       else
+					       cat $SCRIPT_DIR/${pfile}.config \
+						       $SCRIPT_DIR/ipq_debug > $TOP_DIR/.config
+				       fi
+				       ;;
+
+				2)	cat $SCRIPT_DIR/${pfile}.config \
+					       $SCRIPT_DIR/ipq_debug_kasan > $TOP_DIR/.config
+				       ;;
+
+				*)	echo "Wrong input .... exiting"
+					return 0
+					;;
+		       esac
+		       ;;
+
+		'n')
+		       cp $SCRIPT_DIR/${pfile}.config $TOP_DIR/.config
+		       ;;
+		*)
+			echo "Wrong input .... exiting"
+			return 0
+			;;
+	esac
+	echo "CONFIG_TARGET_${qsdk_target}=y" >> $TOP_DIR/.config
+
+	# Set subtarget
+	echo "CONFIG_TARGET_${qsdk_target}_${qsdk_subtarget}=y" >> $TOP_DIR/.config
+	echo "CONFIG_TARGET_${qsdk_target}_${qsdk_subtarget}_${pname}=y" >> $TOP_DIR/.config
+	return 1
+}
+
+read_inputs
+ret_val=$?
+if [ $ret_val != 0 ];then
+	cd $TOP_DIR
+	umask 022
+	make package/symlinks
+	echo -e "\n================= Executing "make defconfig" =============="
+	make defconfig
+
+	echo ""
+	echo '================= .config is generated, you can build using below commands =============='
+	echo ""
+	echo "PLEASE RUN MAKE COMMAND FROM THE LIST OF BUILD OPTIONS AVAILABLE :"
+	echo -e "\t\t make -j8 V=s (Verbose logs)"
+	echo -e "\t\t make -j8 V=e (No detailed logs)"
+	echo -e "\t\t time make -j8 V=s (Verbose logs with total time taken by build)"
+	echo ""
+	echo "************ If you face any error, please rerun with 'make -j1 V=s'.*************"
+	echo ""
 fi
-
-echo "Profile Selected: [$cfg_profile] SOC[$soc] ARCH[$arch]"
-echo ""
-umask 022
-make package/symlinks
-# Copy configs
-cp qca/configs/qsdk/ipq_$cfg_profile.config .config
-echo "CONFIG_TARGET_${soc}=y" >> .config
-echo ""
-echo CONFIG_TARGET_"$soc"=y
-
-if [ "$arch" -eq "64" ]; then
-
-    echo "CONFIG_TARGET_${soc}_generic=y" >> .config
-    echo "CONFIG_TARGET_${soc}_generic_QSDK_${profile}=y" >> .config
-
-    echo "CONFIG_TARGET_${soc}_generic=y"
-    echo "CONFIG_TARGET_${soc}_generic_QSDK_${profile}=y"
-else
-
-    echo "CONFIG_TARGET_${soc}_${soc}_32=y" >> .config
-    echo "CONFIG_TARGET_${soc}_${soc}_32_QSDK_${profile}=y" >> .config
-
-    echo "CONFIG_TARGET_${soc}_${soc}_32=y"
-    echo "CONFIG_TARGET_${soc}_${soc}_32_QSDK_${profile}=y"
-
-fi
-
-# Run "make defconfig"
-echo ""
-echo '================= Executing "make defconfig" =============='
-make defconfig
-echo ""
-echo '================= .config is generated, you can build '$soc' for '$profile' using below commands =============='
-
-echo ""
-echo "PLEASE RUN MAKE COMMAND FROM THE LIST OF BUILD OPTIONS AVAILABLE :"
-echo -e "\t\t make -j8 V=s (Verbose logs)"
-echo -e "\t\t make -j8 V=e (No detailed logs)"
-echo -e "\t\t time make -j8 V=e (Verbose logs with total time taken by build)"
-echo ""
-echo "************ If you face any error, please rerun with 'make -j1 V=s'.*************"
-echo ""
