setup-environment: Add argument support for inputs
Add argument support along with input prompt option for
target, build type, profile and debug profile if required.

Change-Id: I81322a017bf7b2cc90e4218c34f6c950c7174e86
Signed-off-by: Atchaya R <quic_ratchaya@quicinc.com>

diff --git a/setup-environment b/setup-environment
--- a/setup-environment
+++ b/setup-environment
@@ -21,14 +21,17 @@ declare -a debug
 declare -a profile_name
 
 ret_val=1
-if [ "$#" -gt 0 ]; then
-    if [ "$1" == "-h" ]; then
-        echo "Usage: Provide target, arch and profile type for entire build (Please run \"make clean\" if this is an existing workspace)" >&2
-        exit 1
-    fi
-fi
 
 #echo "Help options, Run command with -h [$0 -h]"
+usage()
+{
+	echo "Usage: $0 [-t <ipq807x|ipq60xx|ipq50xx|ipq95xx|ipq53xx>] [-a <32|64>] [-p <256|512|16M|512enterprise|512open|bigendian|enterprise|open|premium>] [-d <y|n>] [-i <Debug|Debug+Kasan>]" 1>&2;
+	echo "For eg:"
+	echo "$0 -t ipq807x -a 32 -p premium -d n"
+	echo "$0 -t ipq53xx -a 64 -p open -d y -i Debug"
+	echo "Please run \"make clean\" if this is an existing workspace"
+	exit 1;
+}
 soc_list=("ipq807x" "ipq60xx" "ipq50xx" "ipq95xx" "ipq53xx")
 arch_list=("32" "64")
 
@@ -47,32 +50,94 @@ populate_profile_list()
 
 read_inputs()
 {
-	echo ""
-	echo -e "\t1) ipq807x ( Hawkeye )"
-	echo -e "\t2) ipq60xx ( Cypress )"
-	echo -e "\t3) ipq50xx ( Maple ) "
-	echo -e "\t4) ipq95xx ( Alder ) "
-	echo -e "\t5) ipq53xx ( Miami ) "
-	read -p "Please enter your choice of target[1..5] : " in_soc
-	echo ""
+	in_soc=""
+	in_arch=""
+	input=""
+	debug_in=""
+	debug_input=""
+	local OPTIND
+	while getopts ":t:a:p:d:i:h" arg;do
+		case "${arg}" in
+			t)
+				in_soc=${OPTARG}
+				if [[ "${in_soc}" != "ipq807x" && "${in_soc}" != "ipq60xx" && "${in_soc}" != "ipq50xx" && "${in_soc}" != "ipq95xx" && "${in_soc}" != "ipq53xx" ]]; then
+					echo -e "\n\033[0;31mInvalid target passed as input - ${in_soc}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			a)
+				in_arch=${OPTARG}
+				if [[ "${in_arch}" != "32" && "${in_arch}" != "64" ]]; then
+					echo -e "\n\033[0;31mInvalid build type passed as input - ${in_arch}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			p)
+				input=${OPTARG}
+				if [[ "${input}" != "256" && "${input}" != "512" && "${input}" != "16M" && "${input}" != "512enterprise" && "${input}" != "512open" && "${input}" != "bigendian" && "${input}" != "enterprise" && "${input}" != "enterprise" && "${input}" != "open" && "${input}" != "premium" ]]; then
+				echo -e "\n\033[0;31mInvalid profile passed as input - ${input}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			d)
+				debug_in=${OPTARG}
+				if [[ "${debug_in}" != "y" && "${debug_in}" != "n" ]]; then
+					echo -e "\n\033[0;31mInvalid debug option passed as input - ${debug_in}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			i)
+				debug_input=${OPTARG}
+				if [[ "${debug_input}" != "Debug" && "${debug_input}" != "Debug+Kasan" ]]; then
+					echo -e "\n\033[0;31mInvalid debug profile passed as input - ${debug_input}\033[0m"
+					usage
+					exit 1
+				fi
+				;;
+			h | *)
+				usage
+				exit 0
+				;;
+		esac
+	done
+	shift "$((OPTIND-1))"
 
-	if [[ $in_soc -lt 1 || $in_soc -gt 5 ]]; then
-	        echo "Wrong input.. exiting"
-		return 0
+	if [ -z $in_soc ]; then
+		echo ""
+		echo -e "\t1) ipq807x ( Hawkeye )"
+		echo -e "\t2) ipq60xx ( Cypress )"
+		echo -e "\t3) ipq50xx ( Maple ) "
+		echo -e "\t4) ipq95xx ( Alder ) "
+		echo -e "\t5) ipq53xx ( Miami ) "
+		read -p "Please enter your choice of target[1..5] : " in_soc
+		echo ""
+
+		if [[ $in_soc -lt 1 || $in_soc -gt 5 ]]; then
+			echo "Wrong input.. exiting"
+			return 0
+		fi
+		in_soc=${soc_list[$in_soc-1]}
 	fi
 
-	echo -e "\t1) 32 Bit"
-	echo -e "\t2) 64 bit"
-	read -p "Please enter your choice of build type[1..2] : " in_arch
-	echo ""
+	if [ -z $in_arch ]; then
+		echo -e "\t1) 32 Bit"
+		echo -e "\t2) 64 bit"
+		read -p "Please enter your choice of build type[1..2] : " in_arch
+		echo ""
 
-	if [[ $in_arch -lt 1 || $in_arch -gt 2 ]]; then
-	        echo "Wrong input.. exiting"
-		return 0
+		if [[ $in_arch -lt 1 || $in_arch -gt 2 ]]; then
+		        echo "Wrong input.. exiting"
+			return 0
+		fi
+		in_arch=${arch_list[$in_arch-1]}
 	fi
 
-	qsdk_target=${soc_list[$in_soc-1]}
-	arch=${arch_list[$in_arch-1]}
+	qsdk_target=$in_soc
+	arch=$in_arch
 	if [ "$arch" -eq "64" ];then
 		qsdk_subtarget="generic"
 	else if [ "$arch" -eq "32" ];then
@@ -80,17 +145,29 @@ read_inputs()
 		fi
 	fi
 
-	echo -e "\n\033[36m**** List of supported QSDK profiles *****\033[0m"
 	populate_profile_list
-	index=1
-	for i in ${profile[@]};do
-		echo -e "\t$index) ${i:4}"
-		index=$(( $index+1 ))
-	done
-	read -p "Choose the profile [1..${#profile[@]}] : " input
-	if [[ $input -lt 1 || $input -gt ${#profile[@]} ]];then
-		echo "Please enter a valid input...Exiting"
-		return 0
+	if [ -z $input ]; then
+		echo -e "\n\033[36m**** List of supported QSDK profiles *****\033[0m"
+		index=1
+		for i in ${profile[@]};do
+			echo -e "\t$index) ${i:4}"
+			index=$(( $index+1 ))
+		done
+		read -p "Choose the profile [1..${#profile[@]}] : " input
+		if [[ $input -lt 1 || $input -gt ${#profile[@]} ]];then
+			echo "Please enter a valid input...Exiting"
+			return 0
+		fi
+	else
+		index=0
+		string="ipq_"$input
+		for i in ${profile[@]};do
+			index=$(( $index+1 ))
+			if [ ${string} == ${i} ]; then
+				break
+			fi
+		done
+		input="$index"
 	fi
 	declare qsdk_profile=${profile[$(( $input -1 ))]}
 	pfile=${profile[$(( $input -1 ))]}
@@ -111,17 +188,31 @@ read_inputs()
 		sed 's/ARCH:=armeb/ARCH:=arm/g' -i $TOP_DIR/target/linux/${qsdk_target}/${qsdk_target}_32/target.mk
 	fi
 
-	read -p "Debug build required ? [y/n] : " debug_in
+	if [ -z $debug_in ]; then
+		read -p "Debug build required ? [y/n] : " debug_in
+	fi
 	case $debug_in in
-		'y') debug=("Debug" "Debug+Kasan")
-			# Check for debug builds
-			index=1
-			for i in ${debug[@]};do
-				echo -e "\t$index) $i"
-				index=$(( $index+1 ))
-			done
+		'y')    debug=("Debug" "Debug+Kasan")
+			if [ -z $debug_input ]; then
+				debug=("Debug" "Debug+Kasan")
+				# Check for debug builds
+				index=1
+				for i in ${debug[@]};do
+					echo -e "\t$index) $i"
+					index=$(( $index+1 ))
+				done
 
-			read -p "Choose the option for debug build : " debug_input
+				read -p "Choose the option for debug build : " debug_input
+			else
+				index=1
+				for i in ${debug[@]};do
+					if [ ${debug_input} == ${i} ]; then
+						break
+					fi
+					index=$(( $index+1 ))
+				done
+				debug_input=$index
+			fi
 			case $debug_input in
 				1)	if [[ "$pname" = QSDK_16M ]];then
 					       cat $SCRIPT_DIR/${pfile}.config \
@@ -158,7 +249,7 @@ read_inputs()
 	return 1
 }
 
-read_inputs
+read_inputs $@
 ret_val=$?
 if [ $ret_val != 0 ];then
 	cd $TOP_DIR
